#!/bin/bash

dir="/home/deadeye/Pictures/wallpapers/"
conf="/home/deadeye/.config/newq/newq.conf"

source "$conf"

usage() {
	echo "USAGE: "
	echo "-h   display this help  "
	echo "-v   display version "
	echo "-c   change default wallpaper "
	echo "-d   apply wallpaper "

}

startup()
{
	pywalfox update;
	#cd && ./alacrittypywal.sh >/dev/null 2>&1 ; 
	cp /home/deadeye/.cache/wal/colors.Xresources /home/deadeye/.Xresources
#	bash /home/deadeye/misc/ChromiumPywal/generate-theme.sh
}

setDefault()
{
    	declare -g default="$(echo $(sxiv -r "$dir" -o))" 
    	echo "Setting default wallpaper to $default"
    	typeset -p default > "$conf"
}

options() {
while getopts "rvcdsh:" flag
do
	case "$flag" in 
		v)
			echo "v1.2" && exit;;
		r)
			wal -q -i "$dir"
			runtime ;;
        c)
        	setDefault ;;
        d)
			wal -q -i $default 
            echo $default
           	startup ;;
		h)
			usage ;;
		?)
			usage && exit 1 ;;		
	esac
done 
}
options "$@"
