#!/bin/bash

dir="$HOME/Pictures/wallpapers/"
conf="$HOME/.config/newq/newq.conf"

. "$conf"

usage() {
	echo "USAGE: "
	echo "-h   display this help  "
	echo "-v   display version "
	echo "-r   set random wallpaper "
	echo "-d   default wallpaper "
	echo "-c   change default wallpaper "
	echo "-s   select wallpaper "

}

runtime()
{
	pywalfox update;
	#cd && ./alacrittypywal.sh >/dev/null 2>&1 ; 
	cp $HOME/.cache/wal/colors.Xresources $HOME/.Xresources
	awesome-client 'awesome.restart()' >/dev/null 2>&1
	bash $HOME/misc/ChromiumPywal/generate-theme.sh
	
}

startup()
{
	pywalfox update;
	#cd && ./alacrittypywal.sh >/dev/null 2>&1 ; 
	cp $HOME/.cache/wal/colors.Xresources $HOME/.Xresources
	bash $HOME/misc/ChromiumPywal/generate-theme.sh
}

setDefault()
{
    	default="$(echo $(sxiv -r "$dir" -o))" 
    	echo "Setting default wallpaper to $default"
    	typeset -p default > "$conf"
}

options() {
while getopts "rvcdsh:" flag
do
	case "$flag" in 
		v)
			echo "v1.2" && exit;;
		r)
			wal -q -i "$dir"
			runtime ;;
        c)
        	setDefault ;;
        d)
			wal -q -i "$default" 
           	startup ;;
		s)
			wpr="$(sxiv -r "$dir" -o)" 
			wal -q -i "$wpr" 
            runtime ;;
		h)
			usage ;;
		?)
			usage && exit 1 ;;		
	esac
done 
}
options "$@"
